### ISSUE TITLE
Add the rest of the finder class

### ISSUE THREAD

**Issue by TenshiLyle** [CodingAvenue/ca-school-proof-library#15]
We need to add the rest of the finder class. I'll group them according to how Php Parser grouped them together, but they can be worked in any order. Note that I don't know yet what some of the class represent in the actual php code, I will have to check on them first. Please update the Wiki each time a new finder class has been introduce.

**Expr**
  - [x] ArrayDimFetch ( When getting an array element e.g $array[0])
  - [ ] ArrayItem ( each item in an array creates an ArrayItem instance)
  - [x] Array_
  - [ ] AssignOp ( Not yet sure what this instance represent )
  - [ ] AssignRef (Not yet sure also what this instance represent, maybe when passing passby ref?)
  - [ ] BinaryOp ( bitwise AND operator, weird they didn't call it BitwiseAnd)
  - [ ] BitwiseNot (bitwise Not operator)
  - [ ] BooleanNot ( is this `$bool = true; !$bool;`?)
  - [ ] Cast
  - [ ] ClassConstFetch
  - [ ] Clone_
  - [ ] Closure ( anonymous functions)
  - [ ] ClosureUse 
  - [ ] ConstFetch
  - [ ] Empty_
  - [ ] Error ( Not yet sure if we need this, since from the doc, this is only used when there is a parsing error and we're on error recovery mode)
  - [ ] ErrorSupress ( not yet sure what this instance represent)
  - [ ] Eval_
  - [ ] Exit_
  - [x] FuncCall
  - [ ] Include_
  - [ ] Instanceof_
  - [ ]  Isset_
  - [ ] List_
  - [ ] MethodClass
  - [ ] New_
  - [x] PostDec
  - [x] PostInc
  - [x] PreDec
  - [x] PreInc
  - [ ] Print_
  - [ ] PropertyFetch
  - [ ] ShellExec
  - [ ] StaticClass
  - [ ] StaticPropertyFetch
  - [ ] Ternary
  - [ ] UnaryMinus
  - [ ] UnaryPlus
  - [ ] YieldFrom
  - [ ] Yield_

**Expr/AssignOp**
  - [ ] BitwiseAnd
  - [ ] BitwiseOr
  - [ ]  BitwiseXor
  - [x]  Concat
  - [ ] Div
  - [ ] Minus
  - [ ] Mod
  - [ ] Mul
  - [ ] Plus
  - [ ] Pow
  - [ ] ShiftLeft
  - [ ] ShiftRight

**Expr/BinaryOp**
  - [x] BitwiseAnd
  - [x] BitwiseOr
  - [x] BitwiseXor
  - [ ] BooleanAnd
  - [ ] BooleanOr
  - [ ] Coalesce
  - [x] Concat
  - [x] Div
  - [x] Equal
  - [x] Greater
  - [x] GreaterOrEqual
  - [x] Identical
  - [ ] LogicalAnd
  - [ ] LogicalOr
  - [ ] LogicalXor
  - [x] Minus
  - [x] Mod
  - [x] Mul
  - [x] NotEqual
  - [x] NotIdentical
  - [x] Plus
  - [x] Pow
  - [x] ShiftLeft
  - [x] ShiftRight
  - [x] Smaller
  - [x] SmallerOrEqual
  - [x] Spaceship

**Expr/Cast**
  - [ ] Array_
  - [ ] Bool_
  - [ ] Double
  - [ ] Int_
  - [ ] Object_
  - [ ] String_
  - [ ] Unset_

**Stmt**
  - [x] Break_
  - [x] Case_
  - [ ] Catch_
  - [ ] ClassConst
  - [ ] ClassLike
  - [ ] ClassMethod
  - [ ] Class_
  - [ ] Const_
  - [ ] Continue_
  - [ ] DeclareDeclare
  - [ ] Declare_
  - [x] Do_
  - [x] Echo_
  - [x] Elseif_
  - [x] Else_
  - [ ] Expression
  - [ ] Finally_
  - [x] For_
  - [ ] Foreach_
  - [x] Function_
  - [ ] Global_
  - [ ] Goto_
  - [ ] GroupUse
  - [ ] HaltCompiler
  - [x] If_
  - [ ] InlineHTML
  - [ ] Interface_
  - [ ] Label
  - [ ] namespace_
  - [ ] Nop
  - [ ] Property
  - [ ] PropertyProperty
  - [x] Return_
  - [ ] StaticVar
  - [ ] Static_
  - [x] Switch_
  - [ ] Throw_
  - [ ] TraitUse
  - [ ] TraitUseAdaptation
  - [ ] Trait_
  - [ ] TryCatch
  - [ ] Unset_
  - [ ] UseUse
  - [ ] Use_
  - [x] While_

**Stmt/TraitUseAdaptation**
  - [ ] Alias
  - [ ] Precedence

**Scalar**
  - [ ] MagicConst

**Scalar/MagicConst**
  - [ ] Class_
  - [ ] Dir
  - [ ] File
  - [ ] Function_
  - [ ] Line
  - [ ] Method
  - [ ] Namespace_
  - [ ] Trait_

**Name**
  - [ ] FullyQualified
  - [ ] Relative

**Direct from the Node namespace**
  - [ ] Arg
  - [ ] Const_
  - [ ] FunctionLike
  - [ ] Identifier
  - [ ] Name
  - [ ] NullableType
  - [ ] Param
  - [ ] VarLikeIdentifier
